version: "3.7"

services:
  postgres:
    container_name: keycloak-nc-postgres
    restart: unless-stopped
    tty: true
    image: postgres
    ports:
      - 5444:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-ncr:/var/lib/postgresql/data
  keycloak:
    container_name: keycloak
    restart: unless-stopped
    tty: true
    command: ["start-dev", "--http-port", "8180"]
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9080:8180
    depends_on:
      - postgres
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=super
      - KC_HOSTNAME_ADMIN=localhost
      - KC_HTTP_RELATIVE_PATH=/auth

volumes:
  postgres-db-ncr:
    name: postgres-db-ncr